function features = get_audio_feature(audio, Fs)

afe = audioFeatureExtractor( ...
        "SampleRate", Fs, ...
        "SpectralDescriptorInput","melSpectrum", ...
        "spectralCentroid",true, ...
        "spectralKurtosis",true, ...
        "pitch", true, ...
        "mfcc", true);
 
features = extract(afe, audio);
[n_frames, n_features, n_samples] = size(features);

% Take median of every frame and normalize the features
features = (features - mean(features, 1));
features = features ./std(features,[],1);
features = reshape(features, [n_frames * n_features n_samples]);